[package]
name = "copycat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
glob = "0.3.0"
