[package]
name = "copycat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ignore = "0.4.18"
notify = "5.0.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
